import Button01 from "@/components/etc/Button01";
import axios from "axios";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import ImgSelectButton from "../imgSelectButton";
import Polybutton from "../polybutton";
import { Metadata } from "next";
import ResultRender from "../resultRender";


export const metadata: Metadata = {
    title: "추론결과페이지",
    description: "Generated by create next app",
};

// 서버에서 폴링을 수행하는 함수
async function GetResult(jobid: string, retries = 5, interval = 4000): Promise<ResultImage | null> {
    const springurl = process.env.SPRING_API;
    for (let i = 0; i < retries; i++) {
        try {
            console.log(`🔁 폴링 시도 ${i + 1}`);
            const res = await axios.get<ResultImage>(`${springurl}/imgresult/${jobid}`);
            if (res.data.status === 'done') {
                console.log(res.data)
                console.log('✅ 결과 도착');
                return res.data;
            }
        } catch (err) {
            // console.error("폴링 실패", err);
        }
        await new Promise(res => setTimeout(res, interval));
    }
    return null;
}

export default async function Page({ params }: { params: { jobid: string } }) {
    const {jobid} = await params; // ✅ await 제거
    const result = await GetResult(jobid);
    
    if (!result) {
    // notFound();
        redirect('/?error=server_err')
    }
    
    return (
        <div className="flex flex-col justify-center items-center gap-1.5 p-2">
            
            <text className="flex flex-col justify-center items-center">
                <h1>{result.message}</h1>
                <p>화면에서 선택해주세요</p>
            </text>
            <ResultRender result={result} jobid={jobid} /> 
        </div>
    );
}
